# HTTP server
server {
    listen 80;
    server_name federation-preventive.ru www.federation-preventive.ru xn----7sbldbigg0dp4b3a2j.xn--p1ai www.xn----7sbldbigg0dp4b3a2j.xn--p1ai;

    # ACME challenge for Let's Encrypt
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
